
# GET /api/posts/ HTTP/1.1
# Host: localhost:5000
# content-type: application/json,
# auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjQ2NTE1MjdkNzQ0NzE1NjdjZmU1NTMiLCJpYXQiOjE1OTg1MzU1Njl9.N-1yIkgoETzLXKgYRd62F0hNGDFU3zte_nWN58RFHAY


# POST /api/user/login HTTP/1.1
# Host: localhost:5000
# content-type: application/json

# {
#     "email": "myEmail@mail.com",
#     "password": "myPassword"
# }

# POST /api/user/register HTTP/1.1
# Host: localhost:5000
# content-type: application/json

# {
#     "name": "myName",
#     "email": "myEmail@mail.com",
#     "password": "myPassword"
# }
